### PR TITLE
Add PyPI release

### PR DESCRIPTION
**Pull request by Cattes**
Hi @StatMixedML, I am planning to use XGBoostLSS in a project, and I encountered dependency problems so I changed the package to be able to better incorporate it into other projects.

The package can now be installed via PyPI (once you merge this PR and add your PyPI Token and create a release)

Here is a list of the changes I made. 
1. I have added a [Pipenv](https://pipenv.pypa.io/en/latest/) environment for local development
2. I have relaxed the package requirements in `setup.py` to allow the dependency resolvers to figure out how to use xgboostlss together with other packages
3. I have added a `tests/` directory and a [Github Action](https://docs.github.com/en/actions) that runs the `pytest` tests for python 3.7, 3.8, 3.9 and 3.10
4. I have added a Github Action that will publish the package to PyPI. You still have to add your PyPI Token to the project secrets.(closes https://github.com/StatMixedML/XGBoostLSS/issues/19). A push to master will release to TestPyPI, [creating a release](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) will publish to the real PyPI
5. Publishing to Test PyPI with the name `gxboostlss` or `xgboost-lss` was not allowed. I received an error stating "The name 'xgboost-lss' is too similar to an existing project." ([see here](https://github.com/Cattes/XGBoostLSS/runs/7414365125?check_suite_focus=true)). I therefore renamed the python package to lss-xgboost

Minor changes:
1. I added more lines to the `.gitignore` file based on a template
2. I added a pyproject.toml and a setup.cfg file used in publishing 
3. I added an example for installation and usage to the readme
4. I added the version to `__init__.py`

Let me know what you think about it. I think allowing XGBoostLSS to be `pip install`able makes the package available to a wider audience.

### CODE REVIEW

**Comment by StatMixedML** [comment]
@Cattes Thanks for the effort!

I agree that making the package available on PyPi would be nice, but renaming the package is not something I prefer. Do we see which package it conflicts with?

I would also prefer using Poetry instead of pipenv. Any reasons you prefer pipenv?

Conditional on that we can keep the name, I would need to go through all the changes you've made before I merge the PR.

**Comment by Cattes** [comment]
> I agree that making the package available on PyPi would be nice, but renaming the package is not something I prefer. I recall that I already had it on TestPyPi for experimental reasons. I just deleted the package. Can you please re-try publishing it on testpypi but with the original xgboostlss name?

Keeping the name would be best. If you already had it on TestPyPI there is a good chance that that was the reason for the conflict. I will check if it works now.

> I would also prefer using Poetry instead of pipenv. Any reasons you prefer pipenv?

I am more experienced with Pipenv and know how to set everything up with that. I used Poetry already but at some point of the CICD Pipeline / Packaging I encountered an Issue and switched back to Pipenv. Do you already have a poetry environment set up that you could commit?

> I`d also prefer not to have the example in the readme, but leave them in a separate section.

I think having a minimal example in the readme is a good addition for people to get started, in addition to the large notebook files. But it's your choice :+1: 

> Can we directly have the package on Python-3.8 version

I have setup CICD for Python 3.7 - 3.10 and all tests run. (see https://github.com/Cattes/XGBoostLSS/actions/workflows/github-action.yml) So theoretically it should work for python 3.7+
I can remove python 3.7 Support (and increase some dependency versions again that I had to decrease for Python 3.7 support) and let the "push to pypi" publishing job only run python3.8. 
Locally, I don't have Python 3.8 at the moment, only 3.9 and 3.10 so I used python3.10 for the Pipfile, but if 3.8 is your preferred python version I can get 3.8.

> I rather prefer not to downgrade the dependency versions of the package. Can we directly use and specify the latest versions of all package-dependencies, also for xgboost-base version, i.e., xgboost-1.6.1. This would make the package more up-to-date as compared with the initial push back in 2021.

Yes. I chose the package versions as high as possible so it runs on python 3.7 - 3.10. Initially, the tests only finished for python 3.9 and 3.10 (see https://github.com/Cattes/XGBoostLSS/actions/runs/2698340565) but I incrementally reduced the versions until they were also running on python 3.7

**Comment by Cattes** [comment]
> > I agree that making the package available on PyPi would be nice, but renaming the package is not something I prefer. I recall that I already had it on TestPyPi for experimental reasons. I just deleted the package. Can you please re-try publishing it on testpypi but with the original xgboostlss name?
> 
> Keeping the name would be best. If you already had it on TestPyPI there is a good chance that that was the reason for the conflict. I will check if it works now.

I have tested the automatic deployment to the test PyPI again, and its now working (https://test.pypi.org/project/xgboostlss/0.1.1/). **A name change is not needed anymore.**

>> Can we directly have the package on Python-3.8 version
>
> I have setup CICD for Python 3.7 - 3.10 and all tests run [...]

I have changed the Python Version in the Pipfile to python3.8. The tests still finish correctly for python 3.7 - 3.10.

**Comment by StatMixedML** [comment]
> I have tested the automatic deployment to the test PyPI again, and its now working

Ok nice, thanks.

> I think having a minimal example in the readme is a good addition for people to get started, in addition to the large notebook files. But it's your choice 

Yes, let's rather have the examples in the separate example folder in order not to overload the readme

> Do you already have a poetry environment set up that you could commit?

I do not have one that is usable. However, there seem to be some consensus that poetry is preferable over pipenv, see [here](https://python.plainenglish.io/poetry-a-better-version-of-python-pipenv-561611a029d1) or [here](https://remastr.com/blog/pip-pipenv-poetry-comparison). Hence, I would still prefer using poetry over pipenv.


Also, I tried to install the test-pypi version and got the following error

image

Do you also encounter these issues?

Also the [setup.py](https://github.com/Cattes/XGBoostLSS/blob/master/setup.py) file states ` python_requires=">=3.7, <4"`. Not sure if we still need the setup.py file when we have poetry or pipenv in place.

Also, in the [distributions/__init__.py](https://github.com/Cattes/XGBoostLSS/blob/master/xgboostlss/distributions/__init__.py#L13) file there is no mention of the Gaussian_AutoGrad. Sure, both the Gaussian and the AutoGrad Gaussian have the same function call. Not sure though if this is incorporated.

I also need to make a change to the beta parameter initialization before we release it to pypi. Will do that and let you know.

**Comment by Cattes** [comment]
> Yes, let's rather have the examples in the separate example folder in order not to overload the readme

Alright, I will remove it from the readme.

> I do not have one that is usable. However, there seem to be some consensus that poetry is preferable over pipenv, see [here](https://python.plainenglish.io/poetry-a-better-version-of-python-pipenv-561611a029d1) or [here](https://remastr.com/blog/pip-pipenv-poetry-comparison). Hence, I would still prefer using poetry over pipenv.

I will check if I can set up the deployment using Poetry :+1: 


> Also, I tried to install the test-pypi version and got the following error
> [...] 
> Do you also encounter these issues?

No, I encountered an Issue because I had a numpy version installed that was too high for the shap package, but I have installed it in a separate pipenv environment from the test-pypi where I set the numpy version fix to 1.22. With that I was able to install it. 
```
[packages]
pandas = "*"
numpy = "==1.22"
xgboost = "*"
shap = "*"
sklearn = "*"
ipykernel = "*"
tqdm = "*"
xgboostlss = {index = "https://test.pypi.org/simple/",version = "==0.1.1"}
```

Do you already have a numpy version installed that is smaller that the version required for installing the package (1.21.6)?

> Also the [setup.py](https://github.com/Cattes/XGBoostLSS/blob/master/setup.py) file states python_requires=">=3.7, <4". Not sure if we still need the setup.py file when we have poetry or pipenv in place.

Yes, I will look into poetry packaging and change up the files accordingly. But I assume in poetry I will also define the required python versions. Is >=3.7 <4 ok for you?

> Also, in the [distributions/init.py](https://github.com/Cattes/XGBoostLSS/blob/master/xgboostlss/distributions/__init__.py#L13) file there is no mention of the Gaussian_AutoGrad in DistributionType = .... Sure, both the Gaussian and the AutoGrad Gaussian have the same function call. Not sure though if this is incorporated.

My intention of the `DistributionType = .... ` line was to improve the static type hints I got in Pycharm. For both, Gauusia_AutoGrad and Gaussian, the Class used has the name `Gaussian` (see https://github.com/Cattes/XGBoostLSS/blob/1c0dc866892ded737b278db53f39585a1790daf0/xgboostlss/distributions/Gaussian.py#L23 and https://github.com/Cattes/XGBoostLSS/blob/1c0dc866892ded737b278db53f39585a1790daf0/xgboostlss/distributions/Gaussian_AutoGrad.py#L26) Since thats the case I think the DistributionType is complete for now.

**Comment by Cattes** [comment]
I had a look at the installation from test pypi in a google colab, and I had to (re)install a few packages to match the requirements defined by this package: https://colab.research.google.com/drive/1p6VsA1mD2_kQzd6l_Cr_D96hCdIGtXaf?usp=sharing

After that I was able to use it. 

Resolving the dependency hell is sadly placed on the user in python ...

**Comment by StatMixedML** [comment]
> I will check if I can set up the deployment using Poetry  

Ok nice, thanks.

> Yes, I will look into poetry packaging and change up the files accordingly. But I assume in poetry I will also define the required python versions. Is >=3.7 <4 ok for you?

A long as we do not encounter any package dependency problems or package downgrading issues, fine with me.

> Do you already have a numpy version installed that is smaller that the version required for installing the package (1.21.6)?

Actually, not. I set up a fresh env with python=3.8 and then installed the pypi test version.

> I had a look at the installation from test pypi in a google colab, and I had to (re)install a few packages to match the requirements defined by this package: https://colab.research.google.com/drive/1p6VsA1mD2_kQzd6l_Cr_D96hCdIGtXaf?usp=sharing

I am not sure if pre-installing packages that are dependencies to the actual package is a valid option. Since we specify the packages with their version, all necessary packages should be installed with their corresponding version using the xgboostlss install command. Maybe poetry resolves the issue.

Also, I have updated the beta initialization and committed it to the master branch. Can you please pull the latest changes, thanks.

**Comment by StatMixedML** [comment]
@Cattes I believe that if we want to also allow `pip install git+https://github.com/StatMixedML/XGBoostLSS.git` we still need the previous setup.py. So we should still keep it with the updated package version dependencies from the poetry-file.

**Comment by Cattes** [comment]
> I am not sure if pre-installing packages that are dependencies to the actual package is a valid option. Since we specify the packages with their version, all necessary packages should be installed with their corresponding version using the xgboostlss install command. Maybe poetry resolves the issue.

The Issue was, that there were import statements inside the `__init__.py` file. Becuase of that `pip` tried to import xgboost etc. before actually installing the packages defined inside `install_requires`. I changed that.


> @Cattes I believe that if we want to also allow pip install git+https://github.com/StatMixedML/XGBoostLSS.git we still need the previous setup.py. So we should still keep it with the updated package version dependencies from the poetry-file.

I have added the setup.py file back to the repository.

---

The Test PyPI db is slow right now and the new releases are not yet visible to `pip install` (it only finds 0.1.1).

You could test it locally by first downloading the wheel and then calling pip install on the wheel file directly 

```shell
wget https://test-files.pythonhosted.org/packages/d1/d3/6b7339ada229e893c506b90aff13d64fb1ab0349109522813e4ec996d50c/xgboostlss-0.1.6-py3-none-any.whl
```
```shell
pip install xgboostlss-0.1.6-py3-none-any.whl
```

**Comment by StatMixedML** [comment]
@Cattes It might take some time until I find the time to re-visit and review the PR.

One thing I noticed is that for the unit-tests, we might want to test the functions more generally and not specifically tailored towards the simulation example.

Thanks!

**Comment by Cattes** [comment]
> @Cattes It might take some time until I find the time to re-visit and review the PR.

Alright, thanks for taking the time! If I can support you somehow let me know.

> One thing I noticed is that for the unit-tests, we might want to test the functions more generally and not specifically tailored towards the simulation example.

Yes, I agree the unit tests should be more detailed. I would suggest opening another Issue for tests though.

I added the one example test because I received a deprecation error from xgboost about the use of the `feval` parameter. Because of that I had to switch to `custom_metric`. Since I did not want to break anything I wrote the test for asserting the results of the gaussian model, before switching the parameter.

**Comment by StatMixedML** [comment]
@Cattes 

> I added the one example test because I received a deprecation error from xgboost about the use of the feval parameter. Because of that I had to switch to custom_metric. Since I did not want to break anything I wrote the test for asserting the results of the gaussian model, before switching the parameter.

Yes, indeed. The `feval` argument has been deprecated since version 1.6.0. and `custom_metric` needs to be used instead. Thanks for highlighting this.

**Comment by Cattes** [comment]
Hi @StatMixedML 

I would suggest to first finish this PR before adding more new features. Keeping things separated helps to reduce complexity.

That being said, we currently have `torch>=1.12.0` and a test case in this PR.

So as long as the `torch.distributions` methods you plan to use are available with torch 1.12.0, nothing should change. If something breaks the test case may identify it. Though a separate PR with more tests would be best for further development.

**Comment by Cattes** [comment]
Hi @StatMixedML 
Did you already have time to have a look at this PR? Is there anything I could help / change about it to get it merged?

**Comment by StatMixedML** [comment]
Hi @Cattes,

thanks again for your effort, really appreciate your PR.

I am planning to release a revised version of both XGBoostLSS and LightGBMLSS soonish, that is more tailored to PyTorch and also including the multivariate extension of XGBoostLSS. This means, I need to re-work the package structure a bit and also modify dependencies etc.

Not sure when I finish this. But I prefer to have the changes in place before I merge the PR. Most of it can be re-cycled I suppose so that there are not too many changes you`d need to incorporate.

Thanks!

**Comment by Cattes** [comment]
> Hi @Cattes,
> 
> thanks again for your effort, really appreciate your PR.
> 
> I am planning to release a revised version of both XGBoostLSS and LightGBMLSS soonish, that is more tailored to PyTorch and also including the multivariate extension of XGBoostLSS. This means, I need to re-work the package structure a bit and also modify dependencies etc.
> 
> Not sure when I finish this. But I prefer to have the changes in place before I merge the PR. Most of it can be re-cycled I suppose so that there are not too many changes you`d need to incorporate.
> 
> Thanks!

Alright, just let me know once you incorporated the changes in this repository and I ill update this pull request :+1:

**Comment by gmgeorg** [comment]
Any updates here with all the recent releases of xgboostllss?

**Comment by StatMixedML** [comment]
@Cattes Hope all is well!

May I ask you to remove the xgboostlss from TestPyPI so that I can continue brining it to PyPI. Thanks!

**Comment by StatMixedML** [comment]
@Cattes Thanks again for your effort, very much appreciated. 

I am closing this since it is now on pypi.

**Pull request closed without merging**
